### ISSUE TITLE
Suggestion for maintaining radius on resize

### ISSUE THREAD

**Issue by cjdowner** [equesy/Egmont-plugin#1]
Great work with this plugin! I just wanted to share this neat trick you may not know about that could help when it comes to resizing.

Perhaps instead of a single layer, the squircle could actually be a combined shape, with each corner set to 'Pin to Corner'. This means clicking and dragging the shape to resize, the radius will be respected.

It's something Apple have done on their official iOS Templates for Sketch.

<img width="488" alt="screen shot 2017-03-10 at 10 19 03" src="https://cloud.githubusercontent.com/assets/2099705/23791708/019a9cda-057c-11e7-8a25-a6467ed9986d.png">

**Comment by interfacemarket** [comment]
@cjdowner Yes, this structure of the shape is very good. Yesterday in the official group of Sketch I wrote about it. We plan to update the plugin for generate this shape :) 

Thank you for suggestion!
